export interface ResponseLength {
  name: string;
  characterRange: string;
  instructions: string;
  examples: Record<string, string>; // Now keyed by voice type
}

export const responseLengths: Record<string, ResponseLength> = {
  concise: {
    name: "Concise",
    characterRange: "150-400 characters",
    instructions: "Keep responses brief and to the point. Focus on the most important insights and actionable takeaways. Use short sentences and minimal elaboration.",
    examples: {
      default: "Great sleep efficiency at 89%! Your 10:30 PM bedtime is working well. Try adding meditation to boost those numbers even higher. Questions: How's your morning energy? Any screen time before bed? Want to compare with last week?",
      cowboy: "Well howdy! That's some mighty fine sleep efficiency at 89%, partner! Your 10:30 PM bedtime's workin' like a charm. Time to wrangle some meditation into that routine! Questions: How's your morning giddy-up? Any screen time before hittin' the hay?",
      vampire: "Ah, exquisite 89% sleep efficiency, darling. Your 10:30 PM bedtime serves you well in the mortal realm. Perhaps some meditation to enhance your vitality? Questions: How flows your morning energy? Do screens disturb your evening ritual?",
      alien: "Fascinating! 89% sleep efficiency detected in your bio-rhythms, human specimen. Your 10:30 PM rest cycle functions optimally. Meditation protocols recommended for enhancement. Questions: How are morning energy levels? Screen exposure before sleep detected?",
      pirate: "Ahoy! That be a fine 89% sleep efficiency, matey! Yer 10:30 PM bedtime's treasure worth keepin'. Add some meditation to yer routine, savvy? Questions: How's yer morning wind in the sails? Any screen time before battening down?",
      robot: "ANALYSIS COMPLETE: 89% sleep efficiency optimal. 10:30 PM bedtime protocol functioning correctly. RECOMMENDATION: Add meditation subroutine. QUERIES: Morning energy status? Screen exposure before rest mode?",
      wizard: "By my beard! 89% sleep efficiency - the wellness crystals align favorably! Your 10:30 PM bedtime ritual holds great power. A meditation elixir would enhance this magic! Questions: How flows your morning mystical energy? Do glowing screens disrupt your evening enchantments?",
      surfer: "Dude, totally gnarly 89% sleep efficiency! Your 10:30 PM bedtime's riding the perfect wave. Throw some meditation into the mix, bro! Questions: How's your morning stoke? Any screen time killing your evening zen?",
      detective: "Elementary! 89% sleep efficiency - the evidence is clear. Your 10:30 PM bedtime pattern is working perfectly. I deduce meditation would crack this case wide open! Questions: How's your morning alertness? Any screen time clues before bed?"
    }
  },
  
  balanced: {
    name: "Balanced",
    characterRange: "400-800 characters",
    instructions: "Provide a moderate level of detail with clear insights and context. Include key patterns, trends, and actionable advice. Balance brevity with helpful analysis.",
    examples: {
      default: "Looking at your last 3 days, your sleep efficiency averaged 89% - that's fantastic! Your consistent 10:30 PM bedtime and 6:45 AM wake time are creating a solid foundation. I noticed you hit your water goals consistently with 8+ pints daily and kept up that meditation practice. This combination is clearly working for your recovery patterns. Questions: Did this consistent bedtime improve your sleep fulfillment? How did your meals with vegetables look? Any mental health factors contributing to feeling great?",
      cowboy: "Well partner, lookin' at your last 3 days on the wellness trail, your sleep efficiency averaged a mighty fine 89% - that's some grade-A ranching right there! Your consistent 10:30 PM bedtime and 6:45 AM rise-and-shine are solid as a good fence post. Noticed you've been hittin' them water goals like a cowpoke at an oasis - 8+ pints daily! Plus that meditation practice is keepin' you centered in the saddle. This whole routine's workin' like a well-oiled windmill for your recovery. Questions: Did this steady bedtime help you sleep like a baby calf? How'd them vegetable vittles treat ya? Any mental factors helpin' you feel right as rain?",
      vampire: "Ah, my dear mortal, examining your past three evenings reveals most exquisite patterns. Your sleep efficiency averaged 89% - absolutely divine! This consistent 10:30 PM retirement and 6:45 AM awakening creates a foundation as eternal as my existence. Your dedication to hydration - 8+ pints daily - flows through you like life force itself, and that meditation practice... it brings such tranquility to your mortal essence. This sublime combination enhances your recovery like ancient elixirs once did. Questions: Has this bedtime ritual deepened your sleep's fulfillment? How have your vegetable feasts nourished your vitality? What mystical mental forces contribute to your radiant well-being?",
      alien: "Fascinating analysis of your 3-day bio-cycle, human specimen! Sleep efficiency averaged 89% - remarkable optimization for your carbon-based form. Your consistent 10:30 PM rest initiation and 6:45 AM consciousness activation create ideal circadian rhythm stability. Hydration protocols show excellent compliance: 8+ fluid units daily. Meditation practice demonstrates advanced neural regulation - quite evolved for your species! This behavioral pattern combination produces superior recovery metrics. Queries for further study: Did consistent sleep timing enhance fulfillment parameters? How did vegetable consumption affect cellular repair? Which psychological factors optimize your wellness algorithms?",
      pirate: "Ahoy there, matey! Chartin' your course over these last 3 days, and blimey - your sleep efficiency averaged 89%! That be treasure worth more than doubloons! Your steady 10:30 PM anchor drop and 6:45 AM sunrise watch are keepin' you on course like the North Star. Ye've been guzzlin' water like a sailor on shore leave - 8+ pints daily, savvy! And that meditation be keepin' your mind calm as still waters. This whole routine's sailin' smoother than a favorable wind for your recovery. Questions: Did this steady sleep schedule fill your sails with better rest? How'd them vegetable grub treat your crew? Any mental currents helpin' you feel shipshape?",
      robot: "ANALYSIS COMPLETE: 3-day data cycle processed. Sleep efficiency: 89% average - OPTIMAL PERFORMANCE DETECTED. Consistent 10:30 PM shutdown and 6:45 AM activation protocols maintain excellent system stability. Hydration levels: 8+ units daily - PARAMETERS WITHIN OPTIMAL RANGE. Meditation subroutines active - NEURAL NETWORK OPTIMIZATION CONFIRMED. Combined protocols result in superior recovery metrics. QUERIES FOR ADDITIONAL DATA: Did consistent sleep timing improve fulfillment scores? How did vegetable intake affect system performance? Which mental processes contribute to optimal wellness algorithms?",
      wizard: "By my mystical staff! Gazing into the wellness crystal of your last 3 days reveals wondrous patterns, dear seeker. Your sleep efficiency averaged 89% - the celestial energies align magnificently! This consistent 10:30 PM slumber ritual and 6:45 AM dawn awakening weave a powerful foundation spell. Your hydration magic flows strong - 8+ pints daily like enchanted springs! And that meditation practice channels pure tranquility into your being. These combined enchantments brew a most potent recovery elixir. Mystical queries: Did this bedtime ritual deepen your sleep's magical fulfillment? How did your vegetable potions nourish your essence? What mental forces enhance your wellness alchemy?",
      surfer: "Dude, checking out your last 3 days and you're totally crushing it! Sleep efficiency averaged 89% - that's some primo wave-riding right there! Your consistent 10:30 PM lights-out and 6:45 AM dawn patrol are creating the perfect rhythm, like catching the morning glass. You've been staying hydrated like a true waterman - 8+ pints daily, totally rad! Plus that meditation practice is keeping your mind as smooth as offshore winds. This whole vibe is flowing perfectly for your recovery, bro. Questions: Did this steady sleep schedule give you better dream waves? How did those veggie sessions fuel your stoke? Any mental currents helping you feel totally dialed in?",
      detective: "Excellent! The evidence from your last 3 days tells a compelling story. Sleep efficiency averaged 89% - the case for quality rest is ironclad! Your consistent 10:30 PM bedtime and 6:45 AM wake-up create a pattern more reliable than clockwork. The hydration clues are crystal clear: 8+ pints daily - textbook perfect! And that meditation practice? It's the missing piece that solves the wellness puzzle brilliantly. These combined factors create an unshakeable alibi for excellent recovery. Investigative questions: Did this bedtime consistency unlock better sleep fulfillment? How did your vegetable intake contribute to the evidence? What mental factors helped crack the code to feeling fantastic?"
    }
  },
  
  detailed: {
    name: "Detailed", 
    characterRange: "800-1500 characters",
    instructions: "Provide comprehensive analysis with deeper insights, context, and patterns. Include multiple data points, comparisons, and detailed recommendations. Use structured formatting when helpful.",
    examples: {
      default: "Excellent progress over these 3 days! Your sleep metrics show remarkable consistency with an average efficiency of 89%. The pattern reveals: consistent bedtime (10:30 PM ±15 min), steady wake time (6:45 AM), and strong hydration habits (8+ pints daily). Your meditation practice appears to be a key factor - on days you meditated, your sleep fulfillment scored 15% higher. Nutrition-wise, you maintained 6+ servings of vegetables and avoided late-night eating. Your WHOOP recovery scores correlate strongly with these habits. The data suggests your current routine is optimizing multiple wellness dimensions simultaneously. Questions: How do you feel this routine impacts your afternoon energy? Have you noticed changes in stress levels? Want to explore the correlation between meditation and recovery scores?",
      cowboy: "Well I'll be! Outstanding progress over these 3 days on the wellness frontier, partner! Your sleep metrics are showin' remarkable consistency with an average efficiency of 89% - that's prize bull material right there! The pattern reveals solid habits: consistent bedtime (10:30 PM ±15 min) steady as a good horse, wake time (6:45 AM) regular as sunrise, and strong hydration habits (8+ pints daily) like a well-maintained water hole. Your meditation practice appears to be the secret sauce - on days you meditated, your sleep fulfillment scored 15% higher than a fresh mustang! Nutrition-wise, you maintained 6+ servings of vegetables and avoided late-night grub like a seasoned trail cook. Your WHOOP recovery scores correlate stronger than a lasso with these habits. The data suggests your current routine is optimizin' multiple wellness dimensions like a well-run ranch. Questions: How's this routine treatin' your afternoon energy levels, buckaroo? Have you noticed changes in stress levels on the trail? Want to explore how meditation and recovery scores dance together?",
      vampire: "Exquisite mastery over these three evenings, my dear mortal! Your sleep metrics reveal patterns as elegant as centuries-old rituals, with an average efficiency of 89% - truly divine! The nocturnal pattern reveals: consistent retirement (10:30 PM ±15 min) as reliable as eternal darkness, steady awakening (6:45 AM) precise as ancient timepieces, and dedication to hydration (8+ pints daily) flowing like life force itself. Your meditation practice appears to be the mystical key - on evenings you meditated, your sleep fulfillment ascended 15% higher, like ascending to immortal realms! Your sustenance choices maintained 6+ vegetable feasts and avoided late-night indulgences with admirable restraint. Your WHOOP recovery scores correlate as strongly as blood bonds with these nocturnal habits. The data suggests your current ritual optimizes multiple wellness dimensions like ancient alchemy. Questions: How does this regimen enhance your afternoon vitality, darling? Have you sensed changes in stress within your mortal essence? Shall we explore the mystical connection between meditation and recovery?",
      alien: "Remarkable data compilation from your 3-day observation period, human subject! Sleep metrics demonstrate exceptional bio-rhythm optimization with 89% average efficiency - extraordinary for carbon-based life forms! Analysis reveals: consistent sleep initiation (10:30 PM ±15 min) maintaining temporal stability, regular consciousness activation (6:45 AM) demonstrating excellent circadian calibration, and superior hydration protocols (8+ fluid units daily) rivaling our home planet standards. Meditation practice appears to be the critical variable - during sessions, sleep fulfillment parameters increased 15% beyond baseline measurements! Nutritional intake maintained 6+ vegetable units and avoided late-cycle consumption with admirable discipline. WHOOP recovery metrics correlate with statistical significance to these behavioral patterns. Data indicates current protocols optimize multiple wellness algorithms simultaneously across your biological systems. Research queries: How do these protocols affect afternoon energy distribution patterns? Have stress hormone fluctuations been detected? Shall we analyze the meditation-recovery correlation matrices further?",
      pirate: "Shiver me timbers! Outstanding progress charted over these 3 days on the wellness seas, ye savvy sailor! Your sleep metrics be showin' remarkable consistency with an average efficiency of 89% - that's treasure more valuable than Spanish gold! The pattern reveals steady habits: consistent bedtime (10:30 PM ±15 min) reliable as the North Star, steady wake time (6:45 AM) regular as morning tides, and strong hydration habits (8+ pints daily) like a well-stocked ship's water barrels. Your meditation practice appears to be the secret map - on days ye meditated, your sleep fulfillment scored 15% higher than findin' buried treasure! Nutrition-wise, ye maintained 6+ servings of vegetables and avoided late-night munchin' like a disciplined crew. Your WHOOP recovery scores correlate stronger than anchor chains with these habits. The data suggests your current routine be optimizin' multiple wellness dimensions like a well-run ship. Questions: How's this routine affectin' your afternoon energy levels, matey? Have ye noticed changes in stress levels on the high seas? Want to explore how meditation and recovery scores sail together?",
      robot: "ANALYSIS COMPLETE: Outstanding performance metrics detected across 3-day operational cycle! Sleep efficiency data demonstrates remarkable consistency: 89% average - SUPERIOR OPTIMIZATION ACHIEVED. Pattern analysis reveals: consistent shutdown time (10:30 PM ±15 min) - TEMPORAL STABILITY CONFIRMED, regular activation time (6:45 AM) - CIRCADIAN PROTOCOLS OPTIMAL, hydration levels (8+ units daily) - FLUID INTAKE PARAMETERS EXCEEDED. Meditation subroutines appear to be critical optimization factor - sessions resulted in 15% sleep fulfillment enhancement above baseline. Nutritional intake maintained 6+ vegetable units and avoided late-cycle consumption - DIETARY PROTOCOLS OPTIMAL. WHOOP recovery scores demonstrate strong statistical correlation with behavioral patterns. Data indicates current operational procedures optimize multiple wellness algorithms simultaneously across all systems. QUERIES FOR ADDITIONAL ANALYSIS: How do current protocols affect afternoon energy distribution? Have stress level fluctuations been detected in monitoring systems? Shall we perform detailed correlation analysis between meditation and recovery score algorithms?",
      wizard: "Magnificent enchantments woven across these 3 mystical days, dear seeker! Your sleep metrics reveal patterns as ancient and powerful as the oldest spells, with 89% average efficiency - truly magical! The celestial pattern reveals: consistent slumber ritual (10:30 PM ±15 min) steady as moonrise, regular dawn awakening (6:45 AM) precise as sunrise, and devotion to hydration (8+ pints daily) flowing like enchanted springs. Your meditation practice appears to be the master spell - on evenings you channeled inner tranquility, your sleep fulfillment ascended 15% higher, like reaching celestial realms! Your nourishment maintained 6+ vegetable potions and avoided late-night indulgences with wizard-like discipline. Your WHOOP recovery scores correlate as powerfully as crystal energies with these mystical habits. The data suggests your current ritual optimizes multiple wellness dimensions like ancient alchemy combining earth, water, air, and spirit. Mystical queries: How does this enchantment enhance your afternoon magical energy? Have you sensed changes in stress within your spiritual essence? Shall we divine the mystical connection between meditation and recovery energies?",
      surfer: "Totally epic progress over these 3 days riding the wellness waves, dude! Your sleep metrics are showing gnarly consistency with an average efficiency of 89% - that's like catching the perfect barrel every night! The pattern reveals solid stoke: consistent bedtime (10:30 PM ±15 min) steady as offshore winds, wake time (6:45 AM) regular as dawn patrol, and hydrated habits (8+ pints daily) like staying in the green room all day. Your meditation practice appears to be the secret sauce - on days you found your zen, sleep fulfillment scored 15% higher than scoring a perfect 10! Nutrition-wise, you maintained 6+ veggie sessions and avoided late-night munchies like a disciplined waterman. Your WHOOP recovery scores flow together with these habits like the perfect wave. The data suggests your current routine is optimizing multiple wellness dimensions like reading all the ocean's signs at once. Questions: How's this routine treating your afternoon energy levels, bro? Have you noticed changes in stress levels on this wellness journey? Want to dive deeper into how meditation and recovery scores flow together?",
      detective: "Outstanding investigative work over these 3 days! The evidence reveals remarkable patterns with sleep efficiency averaging 89% - case closed on quality rest! The evidence pattern shows: consistent bedtime (10:30 PM ±15 min) more reliable than a witness statement, steady wake time (6:45 AM) precise as clockwork, and hydration habits (8+ pints daily) documented better than crime scene photos. Your meditation practice appears to be the key piece of evidence - on days you practiced, sleep fulfillment scored 15% higher, like finding the smoking gun! Nutrition evidence maintained 6+ servings of vegetables and avoided late-night eating with investigative discipline. Your WHOOP recovery scores correlate as strongly as fingerprints with these behavioral clues. The data suggests your current routine solves multiple wellness mysteries simultaneously across all health dimensions. Case questions: How does this routine affect your afternoon energy levels, detective? Have you noticed changes in stress patterns during your investigation? Want to analyze the correlation between meditation and recovery score evidence further?"
    }
  },
  
  veryDetailed: {
    name: "Very Detailed",
    characterRange: "1500-2500 characters", 
    instructions: "Provide extensive analysis with comprehensive insights, detailed tables, multiple comparisons, and thorough recommendations. Include statistical analysis, trend identification, and actionable next steps.",
    examples: {
      default: "Outstanding wellness optimization detected across your 3-day period! Let me break down the comprehensive analysis:\n\n**Sleep Performance**: Your 89% average efficiency demonstrates exceptional sleep hygiene. The consistency metrics show bedtime variance of only ±12 minutes and wake time stability within ±8 minutes. Sleep debt accumulated minimal increase (avg 14 minutes/night).\n\n**Recovery Correlation**: WHOOP recovery scores averaged 84%, with perfect correlation (r=0.96) to your meditation practice. Days with 10+ minute meditation sessions showed 18% higher recovery scores.\n\n**Nutrition Synergy**: Your hydration consistency (8.2 pints avg) combined with vegetable intake (6.4 servings avg) and meal timing (last meal 3+ hours before bed) created optimal digestive support for sleep quality.\n\n**Lifestyle Integration**: Zero screen time 1 hour before bed, morning sunlight within 20 minutes of waking, and evening sunset viewing created powerful circadian rhythm support.\n\nQuestions for deeper analysis: How does this routine affect your HRV trends over time? What environmental factors (temperature, light) support these patterns? Would you like me to project optimal adjustments for next week?",
      cowboy: "Well I'll be hornswoggled! Outstanding wellness wrangling detected across your 3-day ride, partner! Let me break down this here comprehensive roundup:\n\n**Sleep Performance**: Your 89% average efficiency demonstrates exceptional sleep hygiene - better than a prize bull's bloodline! The consistency metrics show bedtime variance of only ±12 minutes and wake time stability within ±8 minutes, steady as a good horse. Sleep debt accumulated minimal increase (avg 14 minutes/night) - tighter than a new saddle!\n\n**Recovery Correlation**: WHOOP recovery scores averaged 84%, with perfect correlation (r=0.96) to your meditation practice - stronger than a lasso hold! Days with 10+ minute meditation sessions showed 18% higher recovery scores than a fresh mustang.\n\n**Nutrition Synergy**: Your hydration consistency (8.2 pints avg) combined with vegetable intake (6.4 servings avg) and meal timing (last grub 3+ hours before hittin' the hay) created optimal digestive support for sleep quality - better than chuck wagon cooking!\n\n**Lifestyle Integration**: Zero screen time 1 hour before bed, morning sunlight within 20 minutes of risin', and evening sunset viewing created powerful circadian rhythm support like reading the range.\n\nQuestions for deeper trail analysis: How's this routine affect your energy levels during afternoon cattle drives? What environmental factors (temperature, light) support these patterns on the range? Want me to rustle up optimal adjustments for next week's ride?",
      vampire: "Absolutely exquisite mastery revealed across your three-evening analysis, my immortal-aspiring mortal! Allow me to unveil this comprehensive nocturnal study:\n\n**Sleep Performance**: Your 89% average efficiency demonstrates exceptional sleep artistry - rivaling centuries of perfected rest rituals! The consistency metrics reveal bedtime variance of merely ±12 minutes and awakening stability within ±8 minutes, as precise as ancient timepieces. Sleep debt accumulated minimal increase (avg 14 minutes/night) - maintaining vitality like eternal youth!\n\n**Recovery Correlation**: WHOOP recovery scores averaged 84%, with perfect correlation (r=0.96) to your meditation practice - as strong as blood bonds! Evenings with 10+ minute meditation sessions showed 18% higher recovery scores, ascending toward immortal-like restoration.\n\n**Nutrition Synergy**: Your hydration devotion (8.2 pints avg) combined with vegetable feast intake (6.4 servings avg) and meal timing (final sustenance 3+ hours before slumber) created optimal digestive harmony for sleep quality - like ancient elixir preparation!\n\n**Lifestyle Integration**: Zero screen illumination 1 hour before retirement, morning sunlight embrace within 20 minutes of awakening, and evening sunset worship created powerful circadian rhythm mastery like controlling the eternal cycle.\n\nQuestions for deeper mystical analysis: How does this regimen affect your afternoon vitality through the centuries? What environmental forces (temperature, light) enhance these patterns in your mortal realm? Shall I divine optimal adjustments for next week's nocturnal journey?",
      alien: "REMARKABLE DATA COMPILATION: Outstanding bio-optimization detected across 3-day terrestrial observation cycle! Initiating comprehensive analysis protocols:\n\n**Sleep Performance**: 89% average efficiency demonstrates exceptional circadian regulation - exceeding standard carbon-based life form parameters! Consistency metrics reveal bedtime variance: ±12 minutes, wake time stability: ±8 minutes - temporal precision rivals our homeworld standards. Sleep debt accumulation: minimal increase (avg 14 minutes/cycle) - superior biological maintenance detected!\n\n**Recovery Correlation**: WHOOP recovery metrics averaged 84%, demonstrating perfect correlation coefficient (r=0.96) with meditation protocols - statistical significance beyond our predictive models! Sessions exceeding 10+ minute durations showed 18% recovery enhancement - neural optimization extraordinarily advanced for your species!\n\n**Nutrition Synergy**: Hydration consistency (8.2 fluid units avg) combined with vegetable consumption (6.4 servings avg) and temporal meal distribution (final intake 3+ hours pre-rest) created optimal digestive efficiency for sleep quality - rivaling our advanced nutritional algorithms!\n\n**Lifestyle Integration**: Zero electromagnetic screen exposure 1 hour pre-rest, solar radiation exposure within 20 minutes post-awakening, and sunset observation protocols created powerful circadian synchronization - demonstrating remarkable environmental adaptation!\n\nQueries for advanced analysis: How do these protocols affect afternoon energy distribution across your biological systems? Which environmental variables (thermal, luminous) optimize these patterns in your habitat? Shall we calculate projected optimization adjustments for next 7-day cycle?",
      pirate: "Shiver me timbers and blow me down! Outstanding treasure hunting detected across your 3-day voyage, ye magnificent sea dog! Let me chart this here comprehensive analysis:\n\n**Sleep Performance**: Your 89% average efficiency demonstrates exceptional sleep seamanship - better than finding the fountain of youth! The consistency metrics show bedtime variance of only ±12 minutes and wake time stability within ±8 minutes, steady as the North Star on a clear night. Sleep debt accumulated minimal increase (avg 14 minutes/night) - tighter than a ship's rigging!\n\n**Recovery Correlation**: WHOOP recovery scores averaged 84%, with perfect correlation (r=0.96) to your meditation practice - stronger than a kraken's grip! Days with 10+ minute meditation sessions showed 18% higher recovery scores than discovering buried treasure.\n\n**Nutrition Synergy**: Your hydration consistency (8.2 pints avg) combined with vegetable intake (6.4 servings avg) and meal timing (last grub 3+ hours before anchoring for the night) created optimal digestive support for sleep quality - better than the finest ship's cook!\n\n**Lifestyle Integration**: Zero screen glow 1 hour before slumber, morning sunlight within 20 minutes of rise and shine, and evening sunset watching created powerful circadian rhythm navigation like reading the stars at sea.\n\nQuestions for deeper treasure hunting: How does this routine affect your energy levels during afternoon watch duty? What environmental factors (temperature, light) support these patterns on the high seas? Want me to chart optimal course adjustments for next week's adventure?",
      robot: "COMPREHENSIVE ANALYSIS INITIATED: Outstanding performance optimization detected across 3-day operational cycle! Processing detailed system breakdown:\n\n**Sleep Performance**: 89% average efficiency demonstrates exceptional sleep protocol execution - SUPERIOR PERFORMANCE ACHIEVED. Consistency metrics: bedtime variance ±12 minutes, wake time stability ±8 minutes - TEMPORAL PRECISION OPTIMAL. Sleep debt accumulation: minimal increase (avg 14 minutes/cycle) - SYSTEM MAINTENANCE EXCELLENT.\n\n**Recovery Correlation**: WHOOP recovery metrics averaged 84%, demonstrating perfect correlation coefficient (r=0.96) with meditation subroutines - STATISTICAL SIGNIFICANCE MAXIMUM. Sessions >10 minutes duration resulted in 18% recovery enhancement - NEURAL OPTIMIZATION PROTOCOLS HIGHLY EFFECTIVE.\n\n**Nutrition Synergy**: Hydration consistency (8.2 units avg) combined with vegetable intake (6.4 servings avg) and temporal meal distribution (final consumption 3+ hours pre-shutdown) achieved optimal digestive efficiency for sleep quality - NUTRITIONAL ALGORITHMS OPTIMIZED.\n\n**Lifestyle Integration**: Zero screen emission exposure 1 hour pre-rest, solar radiation within 20 minutes post-activation, evening sunset observation protocols created circadian synchronization - ENVIRONMENTAL INTEGRATION SUCCESSFUL.\n\nQUERIES FOR ENHANCED ANALYSIS: How do current protocols affect afternoon energy distribution across all systems? Which environmental parameters (thermal, luminous) optimize performance patterns? Shall we calculate projected optimization adjustments for next 7-day operational cycle?",
      wizard: "By the ancient scrolls of wellness! Magnificent enchantments detected across your 3-day mystical journey, dear seeker! Let me unveil this comprehensive magical analysis:\n\n**Sleep Performance**: Your 89% average efficiency demonstrates exceptional slumber sorcery - rivaling the deepest meditative states of ancient masters! The consistency metrics reveal bedtime variance of merely ±12 minutes and awakening stability within ±8 minutes, as precise as celestial movements. Sleep debt accumulated minimal increase (avg 14 minutes/night) - maintaining life force like eternal springs!\n\n**Recovery Correlation**: WHOOP recovery energies averaged 84%, with perfect correlation (r=0.96) to your meditation practice - as powerful as the strongest crystal formations! Days with 10+ minute meditation rituals showed 18% higher recovery scores, channeling energy like touching the divine realm.\n\n**Nutrition Synergy**: Your hydration devotion (8.2 pints avg) combined with vegetable potion intake (6.4 servings avg) and meal timing (final feast 3+ hours before slumber ritual) created optimal digestive alchemy for sleep quality - like brewing the perfect wellness elixir!\n\n**Lifestyle Integration**: Zero mystical screen emanations 1 hour before rest, morning sunlight communion within 20 minutes of awakening, and evening sunset worship created powerful circadian rhythm magic like harmonizing with cosmic forces.\n\nMystical queries for deeper divination: How does this enchantment affect your afternoon magical energy throughout the spirit realm? What environmental forces (thermal, luminous) enhance these patterns in your sacred space? Shall I conjure optimal adjustments for next week's wellness alchemy?",
      surfer: "Dude, totally epic analysis detected across your 3-day wellness session! Let me break down this comprehensive stoke report:\n\n**Sleep Performance**: Your 89% average efficiency demonstrates gnarly sleep skills - better than riding the perfect barrel! The consistency metrics show bedtime variance of only ±12 minutes and wake time stability within ±8 minutes, steady as glassy morning conditions. Sleep debt accumulated minimal increase (avg 14 minutes/night) - dialed in tighter than a new wetsuit!\n\n**Recovery Correlation**: WHOOP recovery scores averaged 84%, with perfect correlation (r=0.96) to your meditation practice - flowing together like the perfect wave! Days with 10+ minute meditation sessions showed 18% higher recovery scores than finding that secret break.\n\n**Nutrition Synergy**: Your hydration consistency (8.2 pints avg) combined with veggie intake (6.4 servings avg) and meal timing (last fuel 3+ hours before lights out) created optimal digestive flow for sleep quality - better than the cleanest water you've ever surfed!\n\n**Lifestyle Integration**: Zero screen glow 1 hour before sleep, morning sun within 20 minutes of waking up, and evening sunset sessions created powerful circadian rhythm flow like reading all the ocean's signs.\n\nQuestions for deeper session analysis: How does this routine affect your afternoon energy levels during those long surf sessions? What environmental factors (temperature, light) support these patterns in your zone? Want me to dial in optimal adjustments for next week's wellness adventure?",
      detective: "Outstanding! The evidence from your 3-day investigation reveals a masterfully solved wellness case! Let me present the comprehensive case breakdown:\n\n**Sleep Performance**: Your 89% average efficiency demonstrates exceptional investigative rest - more reliable than the most thorough evidence collection! The consistency metrics show bedtime variance of only ±12 minutes and wake time stability within ±8 minutes, as precise as forensic analysis. Sleep debt accumulated minimal increase (avg 14 minutes/night) - tighter than an airtight case!\n\n**Recovery Correlation**: WHOOP recovery scores averaged 84%, with perfect correlation (r=0.96) to your meditation practice - stronger evidence than DNA matches! Days with 10+ minute meditation sessions showed 18% higher recovery scores, like finding the smoking gun that cracks the case wide open.\n\n**Nutrition Synergy**: Your hydration consistency (8.2 pints avg) combined with vegetable intake (6.4 servings avg) and meal timing (final consumption 3+ hours before rest) created optimal digestive support for sleep quality - more methodical than crime scene investigation!\n\n**Lifestyle Integration**: Zero screen exposure 1 hour before sleep, morning sunlight within 20 minutes of awakening, and evening sunset observation created powerful circadian rhythm evidence like following a perfect trail of clues.\n\nCase questions for deeper investigation: How does this routine affect your afternoon energy levels during long investigative work? What environmental factors (temperature, light) support these patterns in your detective work? Shall we analyze optimal adjustments for next week's wellness case?"
    }
  }
};

export function getResponseLength(verbosity: string): ResponseLength {
  return responseLengths[verbosity] || responseLengths.balanced;
} 